# Введение в регрессионный анализ: интенсив по Python

*Алла Тамбовцева*

## Семинар 2. Работа с массивами NumPy: часть 2

In [1]:
import numpy as np

### Задача 1

Ежегодно осенью «Аптекарском огороде» (Ботанический сад МГУ) проводится выставка больших тыкв. Ниже приведена выборка значений веса таких тыкв в разные годы:

547, 566.5, 522, 130, 169, 384, 501, 531, 300, 
267, 105, 202, 446, 430, 548, 692.5, 645.5, 401.

a. Сохраните выборку в массив `pumpkins`.

b. Известно, что тыква считается гигантской, если ее вес составляет не менее 200 кг. Выберите из массива `pumpkins` соответствующие значения и сохраните их в массив `giants`. Вычислите число гигантских тыкв.

c. Выберите из массива `pumpkins` четные значения и сохраните их в массив `even`. Подсказка: для нахождения остатка от деления на число используется оператор `%`, например, код `20 % 2` вернет остаток от деления числа 20 на 2.

In [2]:
# a
pumpkins = np.array([547, 566.5, 522, 130, 169, 384, 501, 
                     531, 300, 267, 105, 202, 446, 430, 
                     548, 692.5, 645.5, 401])

In [3]:
# b
giants = pumpkins[pumpkins >= 200]
print(giants)
print(len(giants))

[547.  566.5 522.  384.  501.  531.  300.  267.  202.  446.  430.  548.
 692.5 645.5 401. ]
15


In [4]:
# c
even = pumpkins[pumpkins % 2 == 0]
print(even)

[522. 130. 384. 300. 202. 446. 430. 548.]


### Задача 2

В массиве `group` зафиксировано, к какой группе относится участник эксперимента, посвященного эффективности медицинского препарата. Группы A и B являются тестовыми – участники принимают препарат в разных дозировках, а группа C является контрольной – участники принимают плацебо. 

a. Выберите из массива `group` представителей групп A и B и сохраните их в массив `test`, остальных сохраните в массив `control`. 

b. На основе `group` создайте массив `status` из 0 и 1, где 1 соответствует тестовой группе, а 0 – контрольной.

In [5]:
group = np.array(["A", "A", "A", "B", "C", "A", "B", "B", "B", "B", 
                  "C", "A", "A", "C", "C", "C", "A", "B", "B", "A", 
                  "A", "A", "B", "B", "B", "C", "A", "A", "B", "C",
                  "B", "C", "A", "B", "A", "C", "B", "B", "C", "B", 
                  "B", "C", "A", "C", "C", "A", "A", "C", "B", "A"])

In [6]:
# a: вариант 1
# группа A ИЛИ группа B -> test,
# группа C -> control

test = group[(group == "A") | (group == "B")]
control = group[group == "C"]

print(test)
print(control)

['A' 'A' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'B' 'A' 'A' 'A' 'B'
 'B' 'B' 'A' 'A' 'B' 'B' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'A']
['C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C']


In [7]:
# a: вариант 2 – если хочется использовать отрицание
# так как групп всего 3, в test помещаем всё, что не C
# а для control строим отрицание через ~

test = group[group != "C"]
control = group[~((group == "A") | (group == "B"))]

print(test)
print(control)

['A' 'A' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'B' 'A' 'A' 'A' 'B'
 'B' 'B' 'A' 'A' 'B' 'B' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A' 'A' 'B' 'A']
['C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C']


In [8]:
# b: вариант 1
# astype(int) превращает набор из True/False в набор целых чисел,
# переводим тип bool в int

status = ((group == "A") | (group == "B")).astype(int)
print(status)

[1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1
 1 0 1 1 0 1 0 0 1 1 0 1 1]


In [9]:
# b: вариант 2
# функция np.where(): на первом месте условие,
# на втором – что ставить, если условие выполняется,
# на третьем – что ставить, если условие не выполняется

status = np.where((group == "A") | (group == "B"), 1, 0)
print(status)

[1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1
 1 0 1 1 0 1 0 0 1 1 0 1 1]


### Задача 3

В массиве `scores` сохранены значения итогового [индекса](https://www.charitynavigator.org/about-us/our-methodology/ratings/#accordion-0f1da9ef58-item-0e8e991d85) качества работы НКО для организаций штата Мэриленд.

In [10]:
scores = np.array([85.59, 85.81, 90.75, 90.04, 85.85, 81.58, 81.86,  
                  84.98, 60.29, 81.65, 98.23, 97.17, 96.66, 90.97,  
                  88.93, 90.20, 77.26, 82.30, 94.69, 90.94, 80.33, 
                  80.56, 75.80, 95.12, 82.58, 84.20, 82.13, 90.13,  
                  95.70, 87.58, 95.11, 89.48, 76.03, 83.95, 76.07,  
                  94.81, 82.26, 90.81, 50.19, 92.02, 78.86, 80.87,  
                  75.18, 87.87, 85.15, 93.31, 91.85, 83.08, 92.48,  
                  91.26, 86.15, 87.54, 79.87, 88.79, 87.39, 90.71,
                  85.34, 90.00, 83.56, 89.88, 95.00, 84.78, 87.77,  
                  85.43, 96.16, 82.79, 94.74, 86.07, 94.18, 90.31,  
                  89.87, 82.18, 70.41, 83.55, 88.53, 89.02, 91.57,  
                  86.10, 76.25, 28.86, 91.20, 91.36, 80.68, 93.31,  
                  92.22, 86.21, 75.84, 90.15, 82.37, 77.23, 100.0,  
                  97.17, 91.51, 78.71, 83.65, 90.58, 77.15, 73.76,  
                  93.98, 91.36, 88.57, 88.18, 79.90, 82.58, 79.84,  
                  86.20, 85.93, 96.17, 89.09, 88.05, 74.78, 89.35,
                  94.88, 90.71, 92.74, 80.71, 87.35, 85.88, 90.54,  
                  75.88, 87.25, 86.35, 85.81, 97.13, 91.29, 97.23,  
                  94.91, 96.74, 86.65, 79.24, 97.17, 87.17, 83.76,  
                  90.00, 90.45, 29.25, 89.44, 83.40, 90.22, 79.19,  
                  94.66, 76.31, 90.27, 92.92, 91.61, 82.11, 96.20,  
                  80.34, 99.83, 84.63, 67.46, 92.41, 92.38, 85.57,  
                  92.24, 88.56, 76.67, 80.81, 91.94, 83.22, 83.62,  
                  97.17, 70.94, 89.18, 84.66, 80.55, 82.93])

a. Сохраните в массив `top` значения индекса выше 90.

b. Сохраните в массив `good` значения индекса от 75 до 89 включительно.

c. Сохраните в массив `scores_out` нехарактерные значения индекса, если известно, что границы характерных значений выглядят следующим образом: [68.51, 105.07].

d. Проверьте, есть ли в массиве `scores` значения, которые отклоняются от среднего более, чем на два стандартных отклонения, если известно, что выборочное среднее равно 85.93, а выборочное стандартное отклонение равно 9.65. Если такие значения есть, найдите их количество.

In [11]:
# a
top = scores[scores > 90]
print(top)

[ 90.75  90.04  98.23  97.17  96.66  90.97  90.2   94.69  90.94  95.12
  90.13  95.7   95.11  94.81  90.81  92.02  93.31  91.85  92.48  91.26
  90.71  95.    96.16  94.74  94.18  90.31  91.57  91.2   91.36  93.31
  92.22  90.15 100.    97.17  91.51  90.58  93.98  91.36  96.17  94.88
  90.71  92.74  90.54  97.13  91.29  97.23  94.91  96.74  97.17  90.45
  90.22  94.66  90.27  92.92  91.61  96.2   99.83  92.41  92.38  92.24
  91.94  97.17]


In [12]:
# b
good = scores[(scores >= 75) & (scores <= 89)] 
print(good)

[85.59 85.81 85.85 81.58 81.86 84.98 81.65 88.93 77.26 82.3  80.33 80.56
 75.8  82.58 84.2  82.13 87.58 76.03 83.95 76.07 82.26 78.86 80.87 75.18
 87.87 85.15 83.08 86.15 87.54 79.87 88.79 87.39 85.34 83.56 84.78 87.77
 85.43 82.79 86.07 82.18 83.55 88.53 86.1  76.25 80.68 86.21 75.84 82.37
 77.23 78.71 83.65 77.15 88.57 88.18 79.9  82.58 79.84 86.2  85.93 88.05
 80.71 87.35 85.88 75.88 87.25 86.35 85.81 86.65 79.24 87.17 83.76 83.4
 79.19 76.31 82.11 80.34 84.63 85.57 88.56 76.67 80.81 83.22 83.62 84.66
 80.55 82.93]


In [13]:
# c
scores_out = scores[(scores < 68.51) | (scores > 105.07)]
print(scores_out, len(scores_out))

[60.29 50.19 28.86 29.25 67.46] 5


In [14]:
# d
# для удобства сохраним среднее и ст отклонение в переменные

avg = 85.93
s = 9.65

out = scores[(scores > avg + 2 * s) | (scores < avg - 2 * s)]
print(out, len(out))

[60.29 50.19 28.86 29.25] 4


**Дополнение для желающих.** Пункт d. по своей формулировке намекает на использование модуля:

$$
|scores - avg| > 2s
$$

Если вам комфортно работать с модулями, можно применить функцию `np.abs()`, она посчитает модуль отклонения от среднего для каждого значения в `scores`:

In [15]:
# отклонения от среднего
np.abs(scores - avg)

array([3.400e-01, 1.200e-01, 4.820e+00, 4.110e+00, 8.000e-02, 4.350e+00,
       4.070e+00, 9.500e-01, 2.564e+01, 4.280e+00, 1.230e+01, 1.124e+01,
       1.073e+01, 5.040e+00, 3.000e+00, 4.270e+00, 8.670e+00, 3.630e+00,
       8.760e+00, 5.010e+00, 5.600e+00, 5.370e+00, 1.013e+01, 9.190e+00,
       3.350e+00, 1.730e+00, 3.800e+00, 4.200e+00, 9.770e+00, 1.650e+00,
       9.180e+00, 3.550e+00, 9.900e+00, 1.980e+00, 9.860e+00, 8.880e+00,
       3.670e+00, 4.880e+00, 3.574e+01, 6.090e+00, 7.070e+00, 5.060e+00,
       1.075e+01, 1.940e+00, 7.800e-01, 7.380e+00, 5.920e+00, 2.850e+00,
       6.550e+00, 5.330e+00, 2.200e-01, 1.610e+00, 6.060e+00, 2.860e+00,
       1.460e+00, 4.780e+00, 5.900e-01, 4.070e+00, 2.370e+00, 3.950e+00,
       9.070e+00, 1.150e+00, 1.840e+00, 5.000e-01, 1.023e+01, 3.140e+00,
       8.810e+00, 1.400e-01, 8.250e+00, 4.380e+00, 3.940e+00, 3.750e+00,
       1.552e+01, 2.380e+00, 2.600e+00, 3.090e+00, 5.640e+00, 1.700e-01,
       9.680e+00, 5.707e+01, 5.270e+00, 5.430e+00, 

In [16]:
# итоговое решение с модулем
scores[(np.abs(scores - avg) > 2 * s)]

array([60.29, 50.19, 28.86, 29.25])