# Введение в регрессионный анализ: интенсив по Python

*Алла Тамбовцева*

## Семинар 1. Работа с массивами NumPy: часть 1

### Задача 0

Импортируйте библиотеку `numpy` и создайте следующие массивы:

* массив `numbers` из следующих значений: 3, -1, 7, 8, 10, 11, 2, 7, 5;
* массив `scores` из следующих значений: 10, 8.5, 7.8, 9, 9.2, 6.7;
* массив `names` из следующих значений: Алёна, Борис, Василий, Георгий, Даниил;
* массив `column` из следующих значений: 1, 2, 3, 4, 5, id6.

Выведите массивы на экран с помощью функции `print()`. Проверьте их типы, дописав после названия атрибут `.dtype` (от *data type*).

In [1]:
import numpy as np

In [2]:
numbers = np.array([3, -1, 7, 8, 10, 11, 2, 7, 5])
scores = np.array([10, 8.5, 7.8, 9, 9.2, 6.7])
names = np.array(["Алёна", "Борис", "Василий", "Георгий", "Даниил"])
column = np.array([1, 2, 3, 4, 5, 'id6'])

In [3]:
print(numbers, numbers.dtype)
print(scores, scores.dtype)
print(names, names.dtype)
print(column, column.dtype)

[ 3 -1  7  8 10 11  2  7  5] int64
[10.   8.5  7.8  9.   9.2  6.7] float64
['Алёна' 'Борис' 'Василий' 'Георгий' 'Даниил'] <U7
['1' '2' '3' '4' '5' 'id6'] <U21


### Задача 1

a. Ниже приведен массив `dollars` с ценами на товары в долларах. Создайте массив `rubles` с ценами на те же товары в рублях, ориентируясь на курс 1 доллар = 81.3 рубля.

In [4]:
dollars = np.array([23, 45, 76, 12, 18, 180, 74, 135,
                    56, 34, 70, 80, 138, 144, 16, 48,
                    200, 400, 55, 27, 19, 36, 48, 230])

In [5]:
rubles = dollars * 81.3
print(rubles)

[ 1869.9  3658.5  6178.8   975.6  1463.4 14634.   6016.2 10975.5  4552.8
  2764.2  5691.   6504.  11219.4 11707.2  1300.8  3902.4 16260.  32520.
  4471.5  2195.1  1544.7  2926.8  3902.4 18699. ]


b. Ниже приведен массив `temp_f` со значениями температуры воздуха в градусах по Фаренгейту. Создайте массив `temp_c` со значениями температуры воздуха в градусах по Цельсию, считая, что

$$
t_C = \frac{5}{9}(t_F - 32).
$$

In [6]:
temp_f = np.array([-40, -20, 25, 30, 42, 100, 150, 451])

In [7]:
temp_c = (5 / 9) * (temp_f - 32)
print(temp_c)

[-40.         -28.88888889  -3.88888889  -1.11111111   5.55555556
  37.77777778  65.55555556 232.77777778]


### Задача 2

В массивах `problem01` и `problem02` сохранены баллы, полученные студентами в самостоятельной работе из двух заданий. 

a. Создайте массив `smr` с баллами, полученными за самостоятельную работу.

b. Создайте массив `grades` с оценками за работу в 10-балльной шкале (но без округления), считая, что оценки получаются делением на максимально возможный балл 20.

In [8]:
problem01 = np.array([10, 2, 8, 6, 6, 4, 4, 8, 10, 10])
problem02 = np.array([8, 4, 2, 4, 4, 2, 2, 6, 8, 10])

In [9]:
smr = problem01 + problem02
print(smr)

[18  6 10 10 10  6  6 14 18 20]


In [10]:
grades = smr / 20 * 10
print(grades)

[ 9.  3.  5.  5.  5.  3.  3.  7.  9. 10.]


### Задача 3

В трех массивах сохранены статистические данные по одним и тем же избирательным участкам:

* `valid` – количество действительных бюллетеней;
* `invalid` –  количество недействительных бюллетеней;
* `total` – общее количество зарегистрированных избирателей.

Получите массив `turnout` с явкой на этих избирательных участках (в голосах) и массив `turnout_perc` с явкой (в процентах).

In [11]:
valid = np.array([125, 132, 140, 164, 148, 190, 23, 140, 78, 20])
invalid = np.array([2, 5, 1, 4, 0, 10, 0, 3, 2, 0])
total = np.array([262, 310, 253, 440, 528, 367, 23, 314, 142, 22])

In [12]:
turnout = valid + invalid
turnout_perc = turnout / total * 100
print(turnout)
print(turnout_perc)

[127 137 141 168 148 200  23 143  80  20]
[ 48.47328244  44.19354839  55.7312253   38.18181818  28.03030303
  54.49591281 100.          45.54140127  56.33802817  90.90909091]


### Задача 4

В массиве `x` сохранены значения дискретной случайной величины $X$, в массиве `p` – соответствующие им вероятности. 

a. Вычисление математическое ожидание $E(X) = x_1p_1 + x_2p_2 + \dots + x_np_n$.

b. Вычислите дисперсию $D(X) = E(X^2) - E(X)^2$.

In [13]:
x = np.array([-10, 0, 1, 2, 8, 10, 20])
p = np.array([0.05, 0.05, 0.1, 0.15, 0.3, 0.1, 0.25])

In [14]:
ex = sum(x * p)

In [15]:
dx = sum(x ** 2 * p) - ex ** 2

In [16]:
print("E(X) =", ex, "D(X) =", dx)

E(X) = 8.3 D(X) = 66.00999999999999


### Задача 5

В массиве `female` сохранены значения возраста респондентов женского пола. Вычислите число и долю респондентов, которые:

* являются несовершеннолетними, то есть моложе 18 лет;
* достигли возраста 50 лет (от 50 и старше).

In [17]:
female = np.array([18, 18, 19, 23, 25, 32, 36, 56, 60, 
                   66, 28, 30, 27, 31, 65, 48, 33, 17,
                   45, 16, 18, 19, 21, 28, 29, 47, 52,
                   63, 57, 22, 17, 28, 21, 36, 33, 40])

In [18]:
k = sum(female < 18)
n = len(female)
p1 = k / n
print(k, p1)

3 0.08333333333333333


In [19]:
m = sum(female >= 50)
p2 = m / n
print(m, p2)

7 0.19444444444444445


### Задача 6

В задачнике по теории вероятностей когда-то была задача про Алису, которая встает утром то с правой, то с левой ноги. В массиве `experiment` зафиксированы результаты 30-дневного наблюдения за Алисой:

In [20]:
experiment = np.array(["right", "left", "right", "right", "left", 
                      "left", "left", "right", "left", "right", 
                      "right", "right", "right", "right", "left",
                      "left", "left", "right", "left", "right",
                      "right", "right", "right", "right", "right",
                      "left", "left", "right", "right", "right"])

Вычислите процент дней, когда Алиса вставала а) с правой ноги; б) с левой ноги.

In [21]:
N = len(experiment)
perc1 = sum(experiment == "right") / N * 100
perc2 = sum(experiment == "left") / N * 100
print(perc1, perc2)

63.33333333333333 36.666666666666664
